# Project information
site_name: "Flow-Project"
site_url: https://docs.flow-project.net/
site_author: "Flow-Project Team"
site_description: "Documentation for the Flow-Project, an open-source environment for handwritten text recognition (HTR) and related tasks."
repo_name: The-Flow-Project/flow-docs
repo_url: https://github.com/The-Flow-Project/flow-docs
edit_uri: https://github.com/The-Flow-Project/flow-docs/tree/main/docs

use_directory_urls: false
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Flow-Project: index.md

  - Getting Started:
    - Installation: getting_started/installation.md
    - Overview Environment: htr_workflow/n8n.md

  - Tutorials:
    - Preprocessing a ZIP into a raw XML dataset: tutorials/preprocessing_zip_raw_xml.md
    - Preprocessing from a HuggingFace dataset: tutorials/preprocessing_hf_raw_xml.md
    - Preprocessing a line-based dataset: tutorials/preprocessing_line_based.md
    - Running inference: tutorials/inference.md
    - Evaluating results: tutorials/evaluation.md
    - Writing results back into raw XML: tutorials/write_raw_xml.md

  - Reference:
    - Packages: packages.md
    - Services: services.md

  - Help:
    - FAQ: help/faq.md
    - Contributing: help/contributing.md


# Configuration
theme:
  name: material
  custom_dir: docs/overrides

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - toc.follow

  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/TheFlow_white.png
  # logo: assets/TheFlow_black.png
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date-localized
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/the-flow-project
      name: Github 
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

