name: Deploy Docs

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Docs Deploy
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
      - name: Deploy docs with Mike
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo $latest_tag
          mike deploy --push --update-aliases $latest_tag latest

      - name: Add CNAME to gh-pages root
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "docs.flow-project.net" > CNAME
          git add CNAME
          git diff --cached --quiet || git commit -m "Persist CNAME for custom domain"
          git push origin gh-pages
